sudo: required
dist: trusty

language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-cache search openmpi
 - sudo apt-get install -qq check libopenmpi-dev openmpi-bin check bc libattr1-dev python-pip
 - sudo pip install nose
 - git clone https://github.com/hpc/libcircle.git
 - pushd libcircle
 - ./autogen.sh && ./configure --enable-tests && make && make check && sudo make install
 - popd
 - git clone https://github.com/hpc/lwgrp.git
 - pushd lwgrp
 - ./autogen.sh && ./configure && make && sudo make install
 - popd
 - git clone https://github.com/hpc/dtcmp.git
 - pushd dtcmp
 - ./autogen.sh && ./configure --with-lwgrp=/usr/local && make && sudo make install
 - popd
 - libarchive=libarchive-3.1.2
 - wget http://www.libarchive.org/downloads/${libarchive}.tar.gz
 - tar zxvf ${libarchive}.tar.gz
 - pushd ${libarchive}
 - ./configure && make && sudo make install
 - popd
 - sudo ldconfig
 - ls -ltr /usr/local/lib/libdtcmp*
 - nm /usr/local/lib/libdtcmp.so | grep DTCMP

script: ./autogen.sh && ./configure --with-dtcmp=/usr/local && make && make test

compiler:
  - clang
  - gcc

notifications:
  email:
    - fileutils-dev@googlegroups.com
    - jonb@lanl.gov
    - jon@bringhurst.org
