language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check libopenmpi-dev openmpi-bin check bc libattr1-dev python-pip
 - sudo pip install nose
 - git clone https://github.com/hpc/libcircle.git
 - pushd libcircle
 - ./autogen.sh && ./configure --enable-tests && make && make check && sudo make install
 - popd
 - git clone https://github.com/hpc/lwgrp.git
 - pushd lwgrp
 - ./autogen.sh && ./configure && make && sudo make install
 - popd
 - git clone https://github.com/hpc/dtcmp.git
 - pushd dtcmp
 - ./autogen.sh && ./configure --with-lwgrp=/usr/local && make && sudo make install
 - popd
 - sudo ldconfig

script: ./autogen.sh && ./configure && make && make test

compiler:
  - clang
  - gcc

notifications:
  email:
    - fileutils-dev@googlegroups.com
    - jonb@lanl.gov
    - jon@bringhurst.org
