language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check libopenmpi-dev openmpi-bin

script: ./autogen.sh && ./configure && make && make test

compiler:
  - clang
  - gcc

notifications:
  email:
    - jonb@lanl.gov
    - jon@bringhurst.org
