sudo: required
dist: trusty

language: c

# - sudo apt-get install -qq check mpich check bc libattr1-dev python-pip
before_install:
 - test -n $CC  && unset CC
 - test -n $CXX && unset CXX
 - sudo apt-get update -qq
 - sudo apt-cache search openmpi
 - sudo apt-cache search mpich
 - sudo apt-get install -qq check libopenmpi-dev openmpi-bin check bc libattr1-dev python-pip
 - sudo pip install nose
 - git clone https://github.com/hpc/libcircle.git
 - pushd libcircle
 - ./autogen.sh && ./configure --enable-tests && make && make check && sudo make install
 - popd
 - git clone https://github.com/hpc/lwgrp.git
 - pushd lwgrp
 - ./autogen.sh && ./configure && make && sudo make install
 - popd
 - dtcmp=dtcmp-1.0.3
 - wget https://github.com/hpc/dtcmp/releases/download/v1.0.3/${dtcmp}.tar.gz
 - tar zxvf ${dtcmp}.tar.gz
 - pushd ${dtcmp}
 - ./configure --with-lwgrp=/usr/local && make && sudo make install
 - popd
 - libarchive=libarchive-3.1.2
 - wget http://www.libarchive.org/downloads/${libarchive}.tar.gz
 - tar zxvf ${libarchive}.tar.gz
 - pushd ${libarchive}
 - ./configure && make && sudo make install
 - popd
 - sudo ldconfig

script: ./autogen.sh && export CC=mpicc && ./configure && make && make test
#script: ./autogen.sh && ./configure && make && make test

compiler:
  - clang
  - gcc

notifications:
  email:
    - fileutils-dev@googlegroups.com
    - jonb@lanl.gov
    - jon@bringhurst.org
