---
# This playbook contains build and install for dtcmp

- name: Clone dtcmp repo
  sudo: false
  remote_user: vagrant
  action: git repo=git@github.com:hpc/dtcmp.git dest=/home/vagrant/dtcmp

- name: Build and install dtcmp
  remote_user: vagrant
  shell: chdir=/home/vagrant/dtcmp ./configure --with-lwgrp=/usr/local && make all install
