---
# This playbook contains build and install for dtcmp

- name: Install pkg-config package
  action: apt pkg={{ item }} state=installed
  with_items:
   - build-essential
   - pkg-config
   - libtool
   - autoconf

- name: Clone dtcmp repo
  sudo: false
  remote_user: vagrant
  action: git repo=git@github.com:hpc/dtcmp.git dest=/home/vagrant/dtcmp

- name: Build and install dtcmp
  remote_user: vagrant
  shell: chdir=/home/vagrant/dtcmp ./autogen.sh && ./configure --with-lwgrp=/usr/local && make all install
  shell: chdir=/home/vagrant chown -R vagrant:vagrant dtcmp
