---
# This playbook contains build and install for libcircle

- name: Install pkg-config package
  action: apt pkg={{ item }} state=installed
  with_items:
   - build-essential
   - pkg-config
   - libtool
   - autoconf

- name: Clone libcircle repo
  sudo: false
  remote_user: vagrant
  git: repo=git@github.com:hpc/libcircle.git dest=/home/vagrant/libcircle

- name: Build and install libcircle
  remote_user: vagrant
  shell: chdir=/home/vagrant/libcircle ./configure && make all install
